USE kishoredb;

DROP TABLE student;

CREATE TABLE Employee(ENo INT(3), EName VARCHAR(15), Age INT(2));
DESCRIBE Employee;
INSERT INTO Employee VALUES(1, 'Jack', 30);
INSERT INTO Employee VALUES(2,'Robert', 50);
SELECT * FROM Employee;

ALTER TABLE EMPLOYEE ADD(SALARY INT(5));
ALTER TABLE EMPLOYEE ADD(AGE INT(2));
ALTER TABLE EMPLOYEE RENAME COLUMN SALARY TO Salary;
ALTER TABLE EMPLOYEE DROP COLUMN AGE;
ALTER TABLE EMPLOYEE MODIFY COLUMN ENAME VARCHAR(20);