USE WORLD;
SELECT * FROM CITY;

SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));
SET SESSION sql_mode = CONCAT(@@sql_mode, ',ONLY_FULL_GROUP_BY');

SELECT COUNTRYCODE, NAME FROM CITY GROUP BY COUNTRYCODE;
SELECT NAME, MAX(POPULATION), MIN(POPULATION), COUNTRYCODE FROM CITY GROUP BY COUNTRYCODE;

-- The column(s) in Group By should be necessarily present in the Select statement and vice-versa is not required. 

SELECT NAME, MAX(POPULATION), MIN(POPULATION), COUNTRYCODE FROM CITY GROUP BY COUNTRYCODE HAVING COUNTRYCODE IN('ABW','ALB');
SELECT NAME, POPULATION, COUNTRYCODE FROM CITY WHERE COUNTRYCODE <>'AFG' GROUP BY COUNTRYCODE HAVING COUNTRYCODE = 'AUS';

SELECT NAME, POPULATION, COUNTRYCODE FROM CITY WHERE COUNTRYCODE <>'AFG' GROUP BY COUNTRYCODE HAVING COUNTRYCODE = 'AUS' ORDER BY POPULATION;
SELECT NAME, DISTRICT, POPULATION FROM CITY ORDER BY POPULATION DESC;