-- Check
CREATE TABLE STUDENT4(SNO INT(3), SNAME VARCHAR(15), MARKS INT(3) CHECK(MARKS BETWEEN 60 AND 100));

INSERT INTO STUDENT4 VALUES(101,'RAM',70); -- Valid
INSERT INTO STUDENT4 VALUES(102,'PRASAD', 57); -- Not Valid
SELECT * FROM STUDENT4;

CREATE TABLE LOCATION
(CITY VARCHAR(15) CHECK(CITY IN('HYDERABAD','CHENNAI','BANGALORE')),
COUNTRY VARCHAR(15), PIN INT(6));

INSERT INTO LOCATION VALUES('HYDERABAD','INDIA',123456); -- Valid
INSERT INTO LOCATION VALUES('MUMBAI','INDIA',654321); -- Invalid

-- Default
CREATE TABLE ORDERS(ID INT(5), ORDER_NUMBER INT(5), ORDER_DATE DATETIME DEFAULT NOW());

SELECT NOW();
INSERT INTO ORDERS VALUES(101,78745,'2024-11-29 15:25:10');
INSERT INTO ORDERS (ID,ORDER_NUMBER) VALUES (102,12345);
SELECT * FROM ORDERS;
