CREATE DATABASE KishoreDB;
DROP DATABASE KishoreDB;
CREATE DATABASE IF NOT EXISTS KishoreDB;

USE kishoredb;
CREATE TABLE STUDENT(SNO INT(5), SNAME VARCHAR(20), MARKS INT(3));
DESCRIBE STUDENT;

INSERT INTO STUDENT VALUES(101,'Kishore',87);
INSERT INTO STUDENT(SNO,SNAME,MARKS) VALUES (102,'Kiran',56);
INSERT INTO STUDENT VALUES(103,'Ram', NULL);

SELECT * FROM STUDENT;
SELECT SNO, SNAME, MARKS+10 FROM STUDENT;
DROP TABLE STUDENT;