USE KISHOREDB;

-- Not Null
CREATE TABLE STUDENT1(SNO INT(3) NOT NULL, SNAME VARCHAR(10), MARKS INT(3));
INSERT INTO STUDENT1 VALUES(101,'Arun',50); -- Valid
SELECT * FROM STUDENT1;
INSERT INTO STUDENT1 VALUES(NULL,'Kiran',70); -- Invalid

-- Unique
CREATE TABLE STUDENT2(SNO INT(3) UNIQUE, SNAME VARCHAR(10), MARKS INT(3)); 
INSERT INTO STUDENT2 VALUES(101,'Kapil',90);
-- UNIQUE CONSTRAINT WILL ALLOW ANY NUMBER OF DUPLICATE NULL VALUES, BUT WON'T ALLOW DUPLICATE VALUES LIKE NUMBERS, STRINGS
INSERT INTO STUDENT2 VALUES(NULL,'Ram',80);
INSERT INTO STUDENT2 VALUES(NULL,'Santhosh',50); -- Allowed

-- Primary Key
CREATE TABLE STUDENT3(SNO INT(3) PRIMARY KEY, SNAME VARCHAR(10), MARKS INT(3));

CREATE TABLE STUDENT3
(SNO INT(3), 
SNAME VARCHAR(10), 
MARKS INT(3),
PRIMARY KEY (SNO,SNAME)); -- Composite key

-- Foreign Key Example
-- Parent table
CREATE TABLE SCHOOL(
SNO INT(3),
SNAME VARCHAR(15),
MARKS INT(3),
PRIMARY KEY(SNO));

INSERT INTO SCHOOL VALUES(101,'ARUN',90);
INSERT INTO SCHOOL VALUES(102,'VIMAL',60);
INSERT INTO SCHOOL VALUES(103,'KAMAL',40);

SELECT * FROM SCHOOL;

-- Child table
CREATE TABLE LIBRARY(
SNO INT(3), FOREIGN KEY (SNO) REFERENCES SCHOOL(SNO),
BOOKNAME VARCHAR(5));

INSERT INTO LIBRARY VALUES(101,'PRINCESS'); -- Allowed
INSERT INTO LIBRARY VALUES(108,'BIKE'); -- Not Allowed because value is not present in the Parent table
INSERT INTO LIBRARY VALUES(NULL,'CAR'); -- Allowed

---------------------

-- ON DELETE CASCADE Example
-- Parent table
CREATE TABLE SCHOOL(
SNO INT(3),
SNAME VARCHAR(15),
MARKS INT(3),
PRIMARY KEY(SNO));

INSERT INTO SCHOOL VALUES(101,'ARUN',90);
INSERT INTO SCHOOL VALUES(102,'VIMAL',60);
INSERT INTO SCHOOL VALUES(103,'KAMAL',40);

SELECT * FROM SCHOOL;

-- Child table
CREATE TABLE LIBRARY(
SNO INT(3), BOOKNAME VARCHAR(5),
FOREIGN KEY (SNO) REFERENCES SCHOOL(SNO) ON DELETE CASCADE);

INSERT INTO LIBRARY VALUES(101,'PRINCESS'); -- Allowed
INSERT INTO LIBRARY VALUES(108,'BIKE'); -- Not Allowed because value is not present in the Parent table
INSERT INTO LIBRARY VALUES(NULL,'CAR'); -- Allowed

DELETE FROM SCHOOL WHERE SNO = 101; -- This line deletes the record in the parent table, as well as the corresponding dependent records in the child table because of On Delete Cascade

