USE WORLD;

SELECT * FROM CITY;
-- Creating a View
CREATE VIEW VIEW_EXAMPLE AS SELECT ID, NAME, COUNTRYCODE FROM CITY;

SELECT * FROM VIEW_EXAMPLE;
DROP VIEW VIEW_EXAMPLE;

-- Index
CREATE INDEX IDX_EXAMPLE ON CITY(ID);
DROP INDEX IDX_EXAMPLE ON CITY;

