USE SAKILA;

SELECT * FROM CITY;

-- SingleRow Sub-Query
SELECT COUNTRY_ID FROM CITY WHERE COUNTRY_ID < (SELECT COUNTRY_ID FROM CITY WHERE CITY = 'ABU DHABI');

-- 2nd Maxmium COUNTRY_ID
SELECT MAX(COUNTRY_ID) FROM CITY WHERE COUNTRY_ID < (SELECT MAX(COUNTRY_ID) FROM CITY);

-- 3rd Maximum COUNTRY_ID
SELECT MAX(COUNTRY_ID) FROM CITY WHERE COUNTRY_ID < (SELECT MAX(COUNTRY_ID) FROM CITY WHERE COUNTRY_ID < (SELECT MAX(COUNTRY_ID) FROM CITY));


-- MultiRow Sub-Query
SELECT * FROM CITY WHERE COUNTRY_ID IN (SELECT COUNTRY_ID FROM CITY WHERE COUNTRY_ID >107);

SELECT * FROM CITY WHERE COUNTRY_ID > ANY(SELECT COUNTRY_ID FROM CITY WHERE COUNTRY_ID > 107);

SELECT * FROM CITY WHERE COUNTRY_ID < ALL(SELECT COUNTRY_ID FROM CITY WHERE COUNTRY_ID > 50);


-- MultiRow Sub-Query examples for reference

-- Query to get department name of the employee
SELECT FIRST_NAME, EMPLOYEE_ID, DEPARTMENT_ID,(SELECT DEPARTMENT_NAME FROM 
DEPARTMENTS WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID) DNAME
FROM EMPLOYEES;

/* List out the employees who are having salary less than the maximum salary and also having hire
 date greater than the hire date of an employee who is having maximum salary */
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES WHERE SALARY <
(SELECT MAX(SALARY) FROM EMPLOYEES) AND HIRE_DATE>(SELECT HIRE_DATE FROM EMPLOYEES WHERE SALARY =(SELECT MAX(SALARY) FROM EMPLOYESS));