USE WORLD;

-- STRING FUNCTIONS
SELECT UPPER('Smith');
SELECT UPPER(NAME) FROM CITY;
SELECT LOWER(NAME) FROM CITY;
SELECT LENGTH(NAME) FROM CITY;

-- Print Names of employees whose name has 4 characters
SELECT * FROM CITY WHERE LENGTH(NAME)=4;
SELECT TRIM('  WELCOME  ');
SELECT INSTR('WELCOME','L');

SELECT SUBSTR('ORACLE',2,3);  -- Extract a substring from a string (start at position 2, extract 3 characters):
SELECT SUBSTR('WELCOME',3,5);

SELECT SUBSTRING('ORACLE',2,3);
SELECT SUBSTRING('WELCOME',3,5);

SELECT * FROM CITY;
SELECT SUBSTRING(NAME,1,3) FROM CITY;

SELECT CONCAT('ORACLE','TRAINING');
SELECT CONCAT(NAME,POPULATION) FROM CITY;

-- NUMERIC FUNTIONS
SELECT ABS(-40);
SELECT ABS(40);
SELECT SQRT(25);
SELECT MOD(10,3);
SELECT POWER(2,3);

SELECT TRUNCATE(40.123,2);
SELECT TRUNCATE(40.1246,3);
SELECT TRUNCATE(6786,-1);
SELECT TRUNCATE(876545,-3);
SELECT GREATEST(100,200,500,900);
SELECT LEAST(100,300,4);

-- Date Functions
SELECT CURDATE();
SELECT CURRENT_DATE();
SELECT CURTIME();
SELECT CURRENT_TIME();
SELECT NOW();
SELECT SYSDATE();
SELECT MONTH('2024-11-04');
SELECT YEAR('2024-11-04');
SELECT DAY('2024-11-04');

USE SYS;
SELECT * FROM SYS_CONFIG;
SELECT * FROM SYS_CONFIG WHERE YEAR(SET_TIME) = '2023';
SELECT * FROM SYS_CONFIG WHERE MONTH(SET_TIME)='10';
SELECT * FROM SYS_CONFIG WHERE MONTHNAME(SET_TIME)= 'OCTOBER';

-- Aggregate Functions
SELECT MAX(POPULATION) FROM CITY;
SELECT MIN(POPULATION) FROM CITY;
SELECT SUM(POPULATION) FROM CITY;
SELECT AVG(POPULATION) FROM CITY;
SELECT COUNT(*) FROM CITY;
 








